### ISSUE TITLE
Bug: Missing PHP Closing Tag

### ISSUE THREAD

**Issue by aljawaid** [eSkiSo/Subtaskdate#11]
https://github.com/eSkiSo/Subtaskdate/blob/37173d3da806fafd3cda17e2e1c58a944b36036e/Template/subtask/form.php#L1

The syntax seems wrong @creecros

**Comment by creecros** [comment]
Works fine without it
and it was automiatically removed by https://github.com/PHP-CS-Fixer/PHP-CS-Fixer
I have a feeling it knows what is needed or not
