### ISSUE TITLE
Calendar entry: What is 'undefined'?

### ISSUE THREAD

**Issue by alfredbuehler** [eSkiSo/Subtaskdate#12]
Please allow me to understand this:
![image](https://github.com/eSkiSo/Subtaskdate/assets/2079289/97bd8db3-497e-41c5-b5d7-f2a6869f265a)

**Comment by creecros** [comment]
What are you showing me? It's been awhile since I looked at this.

**Comment by alfredbuehler** [comment]
It's a generated calendar entry for a subtask.

**Comment by creecros** [comment]
Something must have changed in a newer KB release. I'd say I'll take a look, but I'm not sure I'll remember.

**Comment by creecros** [comment]
I also don't remember, calendar being a plugin, when I added this. Could be something changed there as well.

Edit: timeline shows calendar was infact a plugin, around this time, so it might have to do with updates there that aren't jiving with this old plugin.

**Comment by creecros** [comment]
> It's a generated calendar entry for a subtask.

Is it the time, or date, or what? What is undefined?

**Comment by alfredbuehler** [comment]
Yeah, but there is nothing undefined. The subtask is assigned and has a due date.

EDIT: Oops, maybe it's my baby. Let me have a look first.

**Comment by creecros** [comment]
Does this happen with the original calendar plugin or yours? 

Edit: you answered my question with your edit.

**Comment by creecros** [comment]
@alfredbuehler just added you to an email for sidework, if you are interested.

**Comment by alfredbuehler** [comment]
I'm afraid I will don't like it. But let's see first.
