### ISSUE TITLE
Warning: Undefined array key "due_date"

### ISSUE THREAD

**Issue by GusevVictor** [eSkiSo/Subtaskdate#13]
I installed:

- Application version: v1.2.32
- PHP version: 8.2.8
- PHP SAPI: fpm-fcgi
- Auto Email Extended Actions 1.2.5
- SubtaskDueDate 1.1.3

If I add Automatic action for the project: 

- Send email notification of impending subtask due date

Event name = Daily background job for tasks
Duration in days = 1
Choose a column to ignore, when a task is in this column, no emails will be sent. = Backlog

The job returns an error meaasge. The message is

> Warning: Undefined array key "due_date" in /var/www/app/plugins/SendEmailCreator/Action/SubTaskEmailDue.php on line 78

After that there is no any work email notify at all.

Can you fix that please?

**Comment by creecros** [comment]
That's a different plugin
