### ISSUE TITLE
Access createSubtaskdd via python API

### ISSUE THREAD

**Issue by ghost** [eSkiSo/Subtaskdate#7]
Is it possible to access the createSubtaskdd via python API (https://github.com/kanboard/python-api-client)
I try to set the due date but get error:
kanboard.exceptions.KanboardClientException: Method not found

Any ideas?
Thank you,
Matthias

**Comment by eSkiSo** [comment]
Try last release, you may had an older release that did not had the API functions added by @creecros .
I've launched the release now.

**Comment by ghost** [comment]
Thanks a lot, that solved it!
Matthias

**Comment by creecros** [comment]
Need to update plugin version in plugin.php, and website json to new release. If you want a hand maintaining this repo, Id be willing.

**Comment by eSkiSo** [comment]
Released with plugin.php updated.

**Comment by creecros** [comment]
@eSkiSo 

cool beans, fixed plugin name too, spaces prevent the up to date feature from working. I'll take care of that filter too next chance i get.

**Comment by creecros** [comment]
@eSkiSo 

Filter works now. Updated release and website: https://github.com/eSkiSo/Subtaskdate/releases/tag/1.0.4
